/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class triana_util_LinkToNative */

#ifndef _Included_triana_util_LinkToNative
#define _Included_triana_util_LinkToNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     triana_util_LinkToNative
 * Method:    setInputNodes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_triana_util_LinkToNative_setInputNodes
  (JNIEnv *, jobject, jint);

/*
 * Class:     triana_util_LinkToNative
 * Method:    putData
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_triana_util_LinkToNative_putData
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     triana_util_LinkToNative
 * Method:    putComplexData
 * Signature: ([D[DD)V
 */
JNIEXPORT void JNICALL Java_triana_util_LinkToNative_putComplexData
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     triana_util_LinkToNative
 * Method:    process
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_triana_util_LinkToNative_process
  (JNIEnv *, jobject, jstring);

/*
 * Class:     triana_util_LinkToNative
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_triana_util_LinkToNative_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getInputType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_triana_util_LinkToNative_getInputType
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getOutputType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_triana_util_LinkToNative_getOutputType
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getUserHelp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_triana_util_LinkToNative_getUserHelp
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getInterfaceInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_triana_util_LinkToNative_getInterfaceInfo
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getMode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_triana_util_LinkToNative_getMode
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_triana_util_LinkToNative_getData
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getRealData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_triana_util_LinkToNative_getRealData
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getImagData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_triana_util_LinkToNative_getImagData
  (JNIEnv *, jobject);

/*
 * Class:     triana_util_LinkToNative
 * Method:    getSamplingRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_triana_util_LinkToNative_getSamplingRate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif



